-keep class sakura.kooi.dglabunlocker.XposedModuleInit

-repackageclasses
-allowaccessmodification
-overloadaggressively
-keepattributes SourceFile,LineNumberTable
-renamesourcefileattribute SourceFile